### ISSUE TITLE
Question: Can I control which elements of a route animate?

### ISSUE THREAD

**Issue by rchrdnsh** [AndreasFaust/gatsby-plugin-transitions#9]
I have a multi language site and when I switch languages nothing changes except for the text, even through the URL changes. It would be really nice if I could decide that only the words fade out and in but not anything else between routes, as the page is not scrolling to top. Would something like that be possible with your plugin?

**Comment by AndreasFaust** [comment]
Of course (if I understand you correctly). Elements outside of the TransitionProvider do not disappear between routing. And with `TransitionLink` you can give the next rout a `y`-scroll-position (which would be your window.scrollY in the moment of switching languages). I could optimize this in that way, that you can just provide it a function, which gets executed once and must return a number:

```jsx
    <TransitionLink
      to="/page-2"
      style={{ color: "red" }}
      className="my-custom-link"
      mode="immediate"
      y={() => window.scrollY}
    >
      Go to page 2
    </TransitionLink>
```
(Caution: This does not work yet!)

One problem of the current state of the library is, that `TransitionLink` only works inside the `TransitionProvider`, so your navigation cannot be outside of the changing box (that easily). Because this library was made for a certain project, I have not thought about that in the first place, as I did not need this case. I will fix this with version 2.0.0.

**Comment by rchrdnsh** [comment]
I think i actually want to do the opposite, to be honest. I want everything on the page between two routes to stay exactly the same, except the text on the page, which will be switched from one language to another. I hope that clarifies my intentions.

**Comment by AndreasFaust** [comment]
Coming back to this issue, I now understand, what you mean. What you wanted to achieve is not possible, because the plugin transitions the whole views, except for header- or footer-components you want to persist and therefore keep out of the plugin’s scope. Try out the more complex (but, in my opinion, pretty complicated) [gatsby-plugin-transition-link](https://github.com/TylerBarnes/gatsby-plugin-transition-link).

Version `2.0.0` of my plugin has been released just now, which makes it easier to manage those persistent components and enables TransitionLinks and `useTransitionProvider` outside your animated views. See the updated docs, if you're still interested!
